version: '3.8'
services:

  main-service:
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit

  dbStats:
    ports:
      - "6541:5432"


  stats-service:
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit

  dbEwm:
    ports:
      - "6541:5432"

      

