package main.java.ru.practicum.ewm.model;

import lombok.Data;
import lombok.ToString;
import javax.persistence.*;
import java.time.LocalDateTime;

@Data
@ToString
@Entity
@Table(name = "events")
public class Event {
                    @Id
                    @GeneratedValue(strategy = GenerationType.IDENTITY)
                    @Column(name = "id")
    private Long id;

                    @ManyToOne
                    @JoinColumn(name = "initiator_id")
    private User initiator;

                    @ManyToOne
                    @JoinColumn(name = "location_id")
    private Location location;

                    @ManyToOne
                    @JoinColumn(name = "category_id")
    private Category category;
                    @Column(name = "title")
    private String title;
                    @Column(name = "annotation")
    private String annotation;
                    @Column(name = "description")
    private String description;

                    @Column(name = "confirmed_requests")
    private long confirmedRequests;

                    @Column(name = "created_on")
    private LocalDateTime createdOn;

                    @Column(name = "event_date")
    private LocalDateTime eventDate;

                    @Column(name = "is_paid")
    private boolean paid;

                    @Column(name = "participant_limit")
    private long participantLimit;


}
/*
                          "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          "initiator_id" bigint,
                          "location_id" bigint,
                          "category_id" bigint,
                          "title" varchar,
                          "annotation" varchar,
                          "description" varchar,
                          "confirmed_requests" bigint,
                          "created_on" timestamp,
                          "event_date" timestamp,
                          "is_paid" boolean,
                          "participant_limit" bigint,
                          "published_on" timestamp,
                          "is_request_moderation" boolean,
                          "state" varchar,
                          "views" bigint
 */