DROP TABLE IF EXISTS stats CASCADE;


CREATE TABLE IF NOT EXISTS stats
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app          VARCHAR,
    uri          VARCHAR,
    ip           VARCHAR(25),
    request_time TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_statistic PRIMARY KEY (id)
);