CREATE TABLE "events" (
                          "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          "initiator_id" bigint,
                          "location_id" bigint,
                          "category_id" bigint,
                          "title" varchar,
                          "annotation" varchar,
                          "description" varchar,
                          "confirmed_requests" bigint,
                          "created_on" timestamp,
                          "event_date" timestamp,
                          "is_paid" boolean,
                          "participant_limit" bigint,
                          "published_on" timestamp,
                          "is_request_moderation" boolean,
                          "state" varchar,
                          "views" bigint
);

CREATE TABLE "users" (
                         "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "name" varchar,
                         "email" varchar
);

CREATE TABLE "categories" (
                              "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              "name" varchar
);

CREATE TABLE "location" (
                            "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            "lat" bigint,
                            "lon" bigint
);

CREATE TABLE "event_compilations" (
                                      "compilation_id" bigint,
                                      "event_id" bigint
);

CREATE TABLE "compilations" (
                                "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                "title" varchar,
                                "is_pinned" boolean
);

CREATE TABLE "requests" (
                            "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            "status" varchar,
                            "created" timestamp,
                            "event_id" bigint,
                            "request_id" bigint
);

ALTER TABLE "events" ADD FOREIGN KEY ("initiator_id") REFERENCES "users" ("id");

ALTER TABLE "events" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "events" ADD FOREIGN KEY ("location_id") REFERENCES "location" ("id");

ALTER TABLE "event_compilations" ADD FOREIGN KEY ("event_id") REFERENCES "events" ("id");

ALTER TABLE "event_compilations" ADD FOREIGN KEY ("event_id") REFERENCES "compilations" ("id");

ALTER TABLE "requests" ADD FOREIGN KEY ("request_id") REFERENCES "users" ("id");

ALTER TABLE "requests" ADD FOREIGN KEY ("event_id") REFERENCES "events" ("id");